"use client";

import { useEffect, useState } from "react";
import { Loader2, Plus, Trash2, Pencil, X, Check, AlertCircle } from "lucide-react";
import { adminFetch } from "@/lib/admin/client";

type PostRow = { id: number; title: string; slug: string; excerpt: string | null; content: string };

const EMPTY = { title: "", slug: "", excerpt: "", content: "" };
const inputClass =
  "w-full rounded-sm border border-border bg-surface2 px-3.5 py-2.5 text-sm text-fg outline-none transition-colors focus:border-maroon";

export default function AdminBlogPage() {
  const [items, setItems] = useState<PostRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<number | "new" | null>(null);
  const [form, setForm] = useState(EMPTY);
  const [saving, setSaving] = useState(false);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      setItems(await adminFetch<PostRow[]>("/blog"));
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  function startEdit(item?: PostRow) {
    setError(null);
    if (item) {
      setEditingId(item.id);
      setForm({ title: item.title, slug: item.slug, excerpt: item.excerpt ?? "", content: item.content });
    } else {
      setEditingId("new");
      setForm(EMPTY);
    }
  }

  async function save() {
    setSaving(true);
    setError(null);
    try {
      const body = JSON.stringify({
        title: form.title,
        slug: form.slug || undefined, // auto-generated by the backend when left blank
        excerpt: form.excerpt || undefined,
        content: form.content
      });
      if (editingId === "new") {
        await adminFetch("/blog", { method: "POST", body });
      } else if (editingId != null) {
        await adminFetch(`/blog/${editingId}`, { method: "PATCH", body });
      }
      setEditingId(null);
      await load();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  }

  async function remove(id: number) {
    if (!confirm("ይህን ጽሑፍ መሰረዝ ትፈልጋለህ?")) return;
    try {
      await adminFetch(`/blog/${id}`, { method: "DELETE" });
      await load();
    } catch (err: any) {
      setError(err.message);
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between">
        <h1 className="font-display text-2xl text-fg">ብሎግ</h1>
        <button
          onClick={() => startEdit()}
          className="flex items-center gap-1.5 rounded-sm bg-maroon px-4 py-2 font-mono text-xs text-ink hover:opacity-90"
        >
          <Plus size={14} /> አዲስ ጽሑፍ
        </button>
      </div>

      {error && (
        <p className="mt-4 flex items-center gap-2 text-sm text-maroon">
          <AlertCircle size={14} /> {error}
        </p>
      )}

      {editingId !== null && (
        <div className="mt-6 space-y-3 rounded-sm border border-border bg-surface p-5">
          <input
            placeholder="ርዕስ"
            value={form.title}
            onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))}
            className={inputClass}
          />
          <input
            placeholder="slug (ባዶ ብትተወው ራሱ ይፈጥራል)"
            value={form.slug}
            onChange={(e) => setForm((f) => ({ ...f, slug: e.target.value }))}
            className={inputClass}
          />
          <textarea
            placeholder="አጭር መግቢያ (excerpt)"
            rows={2}
            value={form.excerpt}
            onChange={(e) => setForm((f) => ({ ...f, excerpt: e.target.value }))}
            className={inputClass}
          />
          <textarea
            placeholder="ይዘት (Markdown ይደገፋል)"
            rows={10}
            value={form.content}
            onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))}
            className={`${inputClass} font-mono`}
          />
          <div className="flex gap-2">
            <button
              onClick={save}
              disabled={saving}
              className="flex items-center gap-1.5 rounded-sm bg-maroon px-4 py-2 font-mono text-xs text-ink hover:opacity-90 disabled:opacity-60"
            >
              {saving ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />} አስቀምጥ
            </button>
            <button
              onClick={() => setEditingId(null)}
              className="flex items-center gap-1.5 rounded-sm border border-border px-4 py-2 font-mono text-xs text-muted hover:text-fg"
            >
              <X size={14} /> ተወው
            </button>
          </div>
        </div>
      )}

      {loading ? (
        <p className="mt-6 text-sm text-muted">በመጫን ላይ...</p>
      ) : (
        <div className="mt-6 divide-y divide-border rounded-sm border border-border">
          {items.map((item) => (
            <div key={item.id} className="flex items-start justify-between gap-4 p-4">
              <div>
                <p className="font-mono text-[11px] text-muted">/{item.slug}</p>
                <p className="mt-1 font-display text-base text-fg">{item.title}</p>
                {item.excerpt && <p className="mt-1 text-sm text-muted">{item.excerpt}</p>}
              </div>
              <div className="flex shrink-0 gap-2">
                <button
                  onClick={() => startEdit(item)}
                  className="rounded-sm border border-border p-2 text-muted hover:text-fg"
                >
                  <Pencil size={14} />
                </button>
                <button
                  onClick={() => remove(item.id)}
                  className="rounded-sm border border-border p-2 text-muted hover:text-maroon"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            </div>
          ))}
          {items.length === 0 && <p className="p-4 text-sm text-muted">ምንም ጽሑፍ አልተመዘገበም።</p>}
        </div>
      )}
    </div>
  );
}
